# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tactically Didactic
email: anton@redrook.tech
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on software and a little about me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vattay.github.com" # the base hostname & protocol for your site
twitter_username: Lxf77
github_username:  vattay

# Build settings
markdown: kramdown
